# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically update the database schema based on our Java Entity models
spring.jpa.hibernate.ddl-auto=update

# Enable H2 web console to view the database live (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Run server on port 8080
server.port=8080
